### ISSUE TITLE
CellZoom Function 

### ISSUE THREAD

**Issue by ibrahimth** [Sidhant-Chatterjee/Adaptive-Cell-Zooming#1]
Hello
Thank you for sharing your code.
Could you please tell me why in the CellZoom Function, There is no code. In addition, how can we get the same result as in the paper? 

      function [d] = CellZoom(UE, BS)

       for i = 1:1:size(UE,1)
      end
      end

**Comment by Sidhant-Chatterjee** [comment]
Hi,

Thanks for your mail. I’ll see the issue and will get back to you as soon as possible.

Thanks
Sid

Sidhant Chatterjee
M.S. Candidate | Engineering Assistant
Department of Electrical & Computer Engineering
Utah State University
Logan, UT
LinkedIn | Github
+1 (484) 716-2466| Homepage
________________________________

**Comment by ibrahimth** [comment]
Thank you.
I look forward to your reply.

**Comment by Sidhant-Chatterjee** [comment]
Updated. Apologies for missing this function.

**Comment by ibrahimth** [comment]
The size of UE(i,1)) doesn't match the size of   UE(i,2)) 
Index exceeds matrix dimensions.

Error in CellZoom (line 6)
    dist = sqrt((BS(1) - UE(i,1))^2 + (BS(2) - UE(i,2))^2);
Could you please try it?

**Comment by ibrahimth** [comment]
I updated the code , I hope it will be helpful.
```
function [d] = CellZoom(UE, BS)
dis = 0
size(UE,1)
size(UE,2)
for i = 1:1:size(UE,1)
    dist = sqrt((BS(1) - UE(i,1))^2 + (BS(2) - UE(i,2))^2);
    if dis < dist
        dis = dist;
    end
    dist = 0;
    
end
d=dist
end
```
Also in main_script line 205 should be 
  d(ii) = CellZoom(UEList, BS(ii,:));
